project_id = "jhvbfvqhuemuvwgqpskz"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[functions.download-pdf]
verify_jwt = false

[functions.corretora-approve-ticket]
verify_jwt = false

[functions.public-start]
verify_jwt = false

[functions.public-save]
verify_jwt = false

[functions.public-submit]
verify_jwt = false

[functions.rh-requests-list]
verify_jwt = false

[functions.rh-requests-kpis]
verify_jwt = false

[functions.rh-requests-detail]
verify_jwt = false

[functions.rh-approve-request]
verify_jwt = false

[functions.rh-requests-decline]
verify_jwt = false

[functions.adm-requests-list]
verify_jwt = false

[functions.adm-approve-request]
verify_jwt = false

[functions.adm-requests-decline]
verify_jwt = false

[functions.preencher-dados-veiculos]
verify_jwt = false

[functions.processar-n8n-frotas]
verify_jwt = false